services:
  nc-edge:
    image: read.dev.registry.noux.cloud/nc_edge:2.4.1
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      NC_SERIAL: ${NC_SERIAL:?Serial number is missing in the environments.}
      NC_HARDWARE: ${NC_HARDWARE:?Hardware id is missing in the environments.}
    ports:
      - "${WEB_UI:-1337}:1337"
    volumes:
      - nouxcloud-app-data:/app/data

volumes:
  nouxcloud-app-data:
